[package]
name = "more-fs"
version = "0.1.1"
authors = ["Brian Shu <littlebubu.shu@gmail.com>"]
description = """
More filesystem utilities for the Rust programming language
"""
edition = "2018"
readme = "README.md"
license = "MIT/Apache-2.0"
homepage = "https://github.com/oberblastmeister/more-fs"
repository = "https://github.com/oberblastmeister/more-fs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2.3.1"
